### ISSUE TITLE
运行sh  make.sh install 报错

### ISSUE THREAD

**Issue by Pythonisfun** [StickCui/warp-ctc-pytorch#1]
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DWITH_CUDA -DPYTORCH_VER_0_4 -Iwarpctc/core/include -Iwarpctc/src -I/usr/lib64/python2.7/site-packages/torch/lib/include -I/usr/lib64/python2.7/site-packages/torch/lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c warpctc/src/cpu/cpu_ctc.cpp -o build/temp.linux-x86_64-2.7/warpctc/src/cpu/cpu_ctc.o -std=c++11 -fPIC -DTORCH_EXTENSION_NAME=_warp_ctc -D_GLIBCXX_USE_CXX11_ABI=0
/usr/local/cuda/bin/nvcc -DWITH_CUDA -DPYTORCH_VER_0_4 -Iwarpctc/core/include -Iwarpctc/src -I/usr/lib64/python2.7/site-packages/torch/lib/include -I/usr/lib64/python2.7/site-packages/torch/lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c warpctc/src/cuda/gpu_ctc.cu -o build/temp.linux-x86_64-2.7/warpctc/src/cuda/gpu_ctc.o -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -Wno-deprecated-gpu-targets -DTORCH_EXTENSION_NAME=_warp_ctc -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11
unable to execute /usr/local/cuda/bin/nvcc: No such file or directory
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
请问如何解决，谢谢

**Comment by StickCui** [comment]
@Pythonisfun  根据报错信息，你貌似没有正确安装cuda，因为 nvcc 没找到
