### ISSUE TITLE
error in python3 setup.py install

### ISSUE THREAD

**Issue by rajeevbaalwan** [StickCui/warp-ctc-pytorch#2]
I'm using torch 0.4.0 and python 3.6
getting this stack trace when running python3 setup.py install command:::

running install
running bdist_egg
running egg_info
creating warpctc.egg-info
writing warpctc.egg-info/PKG-INFO
writing dependency_links to warpctc.egg-info/dependency_links.txt
writing requirements to warpctc.egg-info/requires.txt
writing top-level names to warpctc.egg-info/top_level.txt
writing manifest file 'warpctc.egg-info/SOURCES.txt'
reading manifest file 'warpctc.egg-info/SOURCES.txt'
writing manifest file 'warpctc.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/warpctc
copying warpctc/__init__.py -> build/lib.linux-x86_64-3.6/warpctc
copying warpctc/warp_ctc.py -> build/lib.linux-x86_64-3.6/warpctc
running build_ext
building 'warpctc._warp_ctc' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/warpctc
creating build/temp.linux-x86_64-3.6/warpctc/src
creating build/temp.linux-x86_64-3.6/warpctc/src/cpu
creating build/temp.linux-x86_64-3.6/warpctc/src/cuda
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -DPYTORCH_VER_0_4 -Iwarpctc/core/include -Iwarpctc/src -I/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include -I/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/rajeev/environments/ds3/include -I/usr/include/python3.6m -c warpctc/src/version.cpp -o build/temp.linux-x86_64-3.6/warpctc/src/version.o -std=c++11 -fPIC -DTORCH_EXTENSION_NAME=warpctc._warp_ctc
In file included from warpctc/src/cpu/version.h:4:0,
                 from warpctc/src/version.cpp:4:
/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/torch/torch.h:3:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Any Help on this ??

**Comment by StickCui** [comment]
@rajeevbaalwan It seems that you haven't installed a `python-dev` package.

You can use the below code to install it:
```Bash
sudo apt-get install python3-dev
```
